server:
  port: 8080

jwt:
  token:
    lifetime: 10m
    signing:
      key: JHPOQIE13948UIFHJ342IOHUJFOIDU3OFID1FOIEDUR1opiIUJ31234POUJDSF3poiJKFD45POF

card:
  key: 8fH3kL9pQ2wEr7yT5vBn1mZx4C0aSdFg

spring:
  liquibase:
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/card_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    liquibase: DEBUG